enhancement: issues/feat/*
bug: issues/fix/*
housekeeping: issues/chore/*
documentation: issues/docs/*
style: issues/style/*
refactoring: issues/refactor/*
performance: issues/perf/*
testing: issues/test/*
continuous integration: issues/ci/*
revert: issues/revert/*